package com.example.yidakitrip.presentation.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val Orange40 = Color(0xFFEF5B2B)

val md_theme_light_primary = Color(0xFFFFBC54)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCBB)
val md_theme_light_onPrimaryContainer = Color(0xFF27002B)
val md_theme_light_secondary = Color(0xFF5D3724)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFEDDBD)
val md_theme_light_onSecondaryContainer = Color(0xFF281805)
val md_theme_light_tertiary = Color(0xFFFD9D09)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCB)
val md_theme_light_onTertiaryContainer = Color(0xFF341000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF341100)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF341100)
val md_theme_light_surfaceVariant = Color(0xFFF1DFD0)
val md_theme_light_onSurfaceVariant = Color(0xFF3B2317)
val md_theme_light_outline = Color(0xFF827568)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE6)
val md_theme_light_inverseSurface = Color(0xFF552000)
val md_theme_light_inversePrimary = Color(0xFFFFB869)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF885200)
val md_theme_light_outlineVariant = Color(0xFFD4C4B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB869)
val md_theme_dark_onPrimary = Color(0xFF482900)
val md_theme_dark_primaryContainer = Color(0xFF673D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCBB)
val md_theme_dark_secondary = Color(0xFFE0C1A3)
val md_theme_dark_onSecondary = Color(0xFF402D17)
val md_theme_dark_secondaryContainer = Color(0xFF58432C)
val md_theme_dark_onSecondaryContainer = Color(0xFFFEDDBD)
val md_theme_dark_tertiary = Color(0xFFFFB692)
val md_theme_dark_onTertiary = Color(0xFF562000)
val md_theme_dark_tertiaryContainer = Color(0xFF7A3000)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF341100)
val md_theme_dark_onBackground = Color(0xFFFFDBCB)
val md_theme_dark_surface = Color(0xFF341100)
val md_theme_dark_onSurface = Color(0xFFFFDBCB)
val md_theme_dark_surfaceVariant = Color(0xFF50453A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C4B5)
val md_theme_dark_outline = Color(0xFF9D8E81)
val md_theme_dark_inverseOnSurface = Color(0xFF341100)
val md_theme_dark_inverseSurface = Color(0xFFFFDBCB)
val md_theme_dark_inversePrimary = Color(0xFF885200)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB869)
val md_theme_dark_outlineVariant = Color(0xFF50453A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFD9D09)